### ISSUE TITLE
use my data to run emvs

### ISSUE THREAD

**Issue by gethubwy** [uzh-rpg/rpg_emvs#9]
https://www.cnblogs.com/wongyi/p/11091048.html 
This is a detail description of my operation,but I met a puzzling problem,when I run the program,it echo as follows：
![图片](https://user-images.githubusercontent.com/26212984/60176770-dc71f080-9849-11e9-9e4d-7b81f3ee8409.png)
beg for help,thank you ～

**Comment by DanielaEsparza** [comment]
The topic of poses is PoseStamped?

**Comment by Yiming-Zhao** [comment]
I guess that the name of pose topic in your rosbag is different from the default. The default name of pose topic is “/optitrack/davis”, The red line in your screenshot indicates there is no pose read from your rosbag. Add option to run the code “ - -pose_topic= name of pose topic in your rosbag “, I had same issue at the first time. If you also use the bag from ROS Gazebo, I think you maybe get same problem with coordinate axis.

**Comment by gethubwy** [comment]
thank you very much 
But  I found that the topic ''/optitrack/davis'' is advertised by a Motion capture system，but I haven‘t a Motion capture system.
Can I use something to alternative solution , I want to use my data to run this system .
Thanks again.

**Comment by gethubwy** [comment]
> The topic of poses is PoseStamped?

yes,this topic is advertised by a Motion capture system，but I haven‘t a Motion capture system.
Can I use something to alternative solution , I want to use my data to run this system .
Thanks ~

**Comment by ghost** [comment]
I want to use my indoor scenes to run your emvs algorithm.(https://github.com/uzh-rpg/rpg_emvs).

I have some problem about a rosbag file. I beg for your help.
When I record a rosbag file , I found that I have no Motion capture system to advertise the topic ''/optitrack/davis'' ,which is  geometry_msgs/PoseStamped message type.

I use "roslaunch dvs_renderer davis_mono.launch"  (https://github.com/uzh-rpg/rpg_dvs_ros) to use my davis ,and meanwhile use "rosbag record -a "to record my rosbag file.

****Is there any way to use this EMVS algorithm without applying motion capture system?****

Thanks for your help in advance.  @DanielaEsparza @Yiming-Zhao @

**Comment by supitalp** [comment]
Hello,

By definition, the EMVS algorithm requires the camera trajectory to work.
If no motion capture is available, you may:

  1. estimate the camera pose online using an algorithm such as [EVO](http://rpg.ifi.uzh.ch/docs/RAL16_EVO.pdf) (which is not available open source, however), or
  2. if you have access to normal frames, you could also run a visual odometry algorithm such as [SVO](https://github.com/uzh-rpg/rpg_svo) on the frames to get the camera pose necessary for EMVS.

**Comment by gethubwy** [comment]
Thank you for taking time out of your busy schedule to answer my question.
Like you said, maybe I just have to try the second advice.​
(have access to normal frames, and run SVO on the frame to get the camera pose for EMVS)
Thank you very much​~

**Comment by gethubwy** [comment]
I want to use SVO to get camera pose, but  I can not successful initialization. because the camera on DaVis 240C ，which has a resolution of 240*180. It is too low than a universal camera.
then I tried the ORB SLAM2, and the question remains.
That is, I could not run a visual odometry algorithm to get the camera pose ... soooo sad.
Is there any solution to use DaVis 240C to run the EMVS algo? maybe Switch to a higher resolution camera？I don't know the feasibility。
 @supitalp

**Comment by supitalp** [comment]
Hi,

We have often successfully used SVO to obtain camera poses with the frames from the DAVIS240C, so it should be possible.
However, you may need to adjust some parameters to deal with the smaller sensor resolution, Notably, it should help to reduce the number of pyramid levels (maybe to 2?), and the min/max KLT levels. Also try to play with the reprojection error threshold (increase its value a bit). See the parameters here: https://github.com/uzh-rpg/rpg_svo/blob/master/svo/src/config.cpp#L28

If you really do not manage to get results with SVO 1.0, you may try to use SVO 2.0, which is much more robust. Binaries are available on our website (for non-commercial use): http://rpg.ifi.uzh.ch/svo2.html

Here is a set of parameters that works for tracking on the DAVIS240C frames, with SVO 2.0:

```
# IMU topic
use_imu: False

map_scale: 1.0

# Vision parameters
init_min_features: 50
grid_size: 18
init_min_inliers: 35
init_min_disparity: 35
klt_max_level: 3
quality_min_fts: 35
kfselect_numkfs_lower_thresh: 40
kfselect_criterion: FORWARD

img_align_min_level: 0
img_align_max_level: 3
reproj_err_thresh: 6.0
seed_convergence_sigma2_thresh: 150.0
```

Hope that helps.

**Comment by gethubwy** [comment]
Thank you so much~  I'll try again.

**Comment by Lucksong** [comment]
Ｈi,@gethubwy,did solve it?
